### PR TITLE
More annotations, some changes to constants and macros

### PR DESCRIPTION
**Pull request by PikalaxALT**

### CODE REVIEW

**Comment by yenatch** [comment]
What does 4c480a2 do? Is it just a merge commit?

**Comment by PikalaxALT** [comment]
Pretty much, it’s a pull/merge to apply changes made in 303 to my branch.






- Scott Norton
scnorton@mail.med.upenn.edu





From: yenatch
Sent: ‎Friday‎, ‎July‎ ‎24‎, ‎2015 ‎3‎:‎07‎ ‎PM
To: kanzure/pokecrystal
Cc: Scott Norton





What does 4c480a2 do? Is it just a merge commit?

**Comment by kanzure** [comment]
Yeah, merging separately other than changes would be helpful because we can then review the merge, and then we can review the extra changes you are proposing.

**Comment by PikalaxALT** [comment]
I don't think we're seeing the same diff here.

**Comment by yenatch** [comment]
Please commit `constants/radio_constants.asm`.

**Pull request merged**
